version: '3.2'
services:
  param_svr:
    image: "bz/mario-kart-a3c:0.0.2"
    entrypoint: /bin/bash
    tty: true
    volumes:
     - type: bind
       source: .
       target: /src/universe-starter-agent
     - type: bind
       source: /home/brian/Programming/gym-mupen64plus
       target: /src/gym-mupen64plus
     - type: volume
       source: mklogs
       target: /tmp/marioKartLogs

  worker:
    image: "bz/mario-kart-a3c:0.0.2"
    entrypoint: /bin/bash
    tty: true
    volumes:
     - type: bind
       source: .
       target: /src/universe-starter-agent
     - type: bind
       source: /home/brian/Programming/gym-mupen64plus
       target: /src/gym-mupen64plus
     - type: volume
       source: ROMs2
       target: /src/gym-mupen64plus/gym_mupen64plus/ROMs
     - type: volume
       source: mklogs
       target: /tmp/marioKartLogs
    depends_on:
     - param_svr

volumes:
  ROMs2:
  mklogs:
